### ISSUE TITLE
Links to Enums and Structs are broken

### ISSUE THREAD

**Issue by AnastasiyaBritanova** [smartdevicelink/sdl_hmi_integration_guidelines#11]
Currently, links from API description [(example)](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/UI/AddCommand/index.md#request) to related Enums and Structs of Common Interface lead to "Page not found" by the reason:
-> current link: https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/common/structs/index.md#image
-> should be: https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/Common/Structs/index.md#image

The whole Guideline document is impacted.

**Comment by justinjdickow** [comment]
Looking into if making this case insensitive is the correct solution.

**Comment by jacobkeeler** [comment]
The developer portal uses lower case paths, these links do not need to work when used in this repository.
