### ISSUE TITLE
Missing vrHelp parameter for PerformInteraction under VR section.

### ISSUE THREAD

**Issue by mtimmara** [smartdevicelink/sdl_hmi_integration_guidelines#138]
Missing vrHelp parameter for PerformInteraction here: https://smartdevicelink.com/en/docs/hmi/master/vr/performinteraction/. 

The vrHelp parameter is included here (https://smartdevicelink.com/en/docs/hmi/master/ui/performinteraction/) just not under the VR section. 

![image](https://user-images.githubusercontent.com/22474263/54709448-e0d89000-4b1b-11e9-917f-4cc11072956e.png)

**Comment by jacobkeeler** [comment]
See https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L4700

`vrHelp` is not a parameter in the `UI.PerformInteraction` method. This reflects the HMI API and not the mobile API. In the case of `PerformInteraction`, the parameters sent by the mobile device are split between the UI and VR components.
