### ISSUE TITLE
Update Diagram: Revoked App Should Not Be Unregistered by SDL

### ISSUE THREAD

**Issue by AnastasiyaBritanova** [smartdevicelink/sdl_hmi_integration_guidelines#18]
If the app gets revoked by Policies update - SDL should notify HMI about the event, keep such app registered and in NONE level and disallow its activation.

The documentation defect (diagram 13.1.4.2) must be fixed to align with the above.

Raised by issue smartdevicelink/sdl_core#798

**Comment by jacobkeeler** [comment]
Seems this is documented in the `SDL.OnAppPermissionChanged` section: https://smartdevicelink.com/en/guides/hmi/sdl/onapppermissionchanged/
