### ISSUE TITLE
Incorrect sequence diagram for AddCommand Positions in HMI Docs

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_hmi_integration_guidelines#192]
https://smartdevicelink.com/en/guides/hmi/ui/addcommand/
In the sequence diagram for "AddCommand positions"
It shows this:

![image](https://user-images.githubusercontent.com/12956244/75162896-464ddd00-56ec-11ea-874f-9019b15df819.png)

However, if this is what the app sent thyen the menu would be 
Test_3
Test_1
Test_2

I think you should ujst update the signal being sent from the app to say 
UI.AddCommand {appID_1, cmdID_3, position: *1*, menuName: "Test_3"}
This shows a good use of the position field

**Comment by iCollin** [comment]
Closed via #208
