### ISSUE TITLE
Describe unsupported interfaces ("IsReady: false" response)

### ISSUE THREAD

**Issue by AnastasiyaBritanova** [smartdevicelink/sdl_hmi_integration_guidelines#20]
Describe SDL behaviour in cases:
1. interface is not available: response `IsReady(available: false)`
2. interface availability is unknown: non-response
3. interface is available: response `IsReady(available: true)`

Impacted interfaces: 
- UI
- TTS
- VR
- Navigation
- VehiclaeInfo

**Comment by jacobkeeler** [comment]
Seems this was covered by #21
