### ISSUE TITLE
Links in docs/UI/SetDisplayLayout/index.md are broken

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_hmi_integration_guidelines#29]
In ```SetDisplayLayout``` index.md file, the link [Common.DisplayCapabilities](https://github.com/BrandonHe/sdl_hmi_integration_guidelines/blob/master/docs/common/structs/#displaycapabilities), [Common.ButtonCapabilities](https://github.com/BrandonHe/sdl_hmi_integration_guidelines/blob/master/docs/common/structs/#buttoncapabilities), [Common.SoftButtonCapabilities](https://github.com/BrandonHe/sdl_hmi_integration_guidelines/blob/master/docs/common/structs/#softbuttoncapabilities) and [Common.PresetBankCapabilities](https://github.com/BrandonHe/sdl_hmi_integration_guidelines/blob/master/docs/common/structs/#presetbankcapabilities) are all broken, because the link address should be "Common/Structs/index.md#" instead of "common/structs/#"

**Comment by jacobkeeler** [comment]
@BrandonHe These links are not meant for use in the GitHub repository. They are use in a separate way on the documentation site. If you look [here](https://smartdevicelink.com/en/docs/hmi/master/ui/setdisplaylayout/) these links are not broken.

Closing this issue.
