### ISSUE TITLE
Supported icons documentation

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_hmi_integration_guidelines#4]
In the Ford developer portal, there is a static list of supported icons when using `AddCommand` and `Show`. These are missing from the HMI integration guidelines.

Reference: https://developer.ford.com/pages/supported-icons-for-developers-android

**Comment by AnastasiyaBritanova** [comment]
@CMaylone please give more of details:
1. Are you referring `"ImageType"` enum -> `STATIC` value (that apps can use within `"Image"` struct)?
2. Is this icons list Ford-HeadUnit specific?

**Comment by jacobkeeler** [comment]
Static Icons are now documented in the [SDL Overview Guides](https://smartdevicelink.com/en/guides/sdl-overview-guides/user-interface/static-icons/)
